"""Add years_active column to smes table

Revision ID: 002
Revises: 001_add_approved_amount
Create Date: 2026-01-26 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001_add_approved_amount'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smes', sa.Column('years_active', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smes', 'years_active')
    # ### end Alembic commands ###
