"""Update finance request relationships

Revision ID: 19972ff781b0
Revises: 450f0960a5fb
Create Date: 2025-11-03 12:59:19.335419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19972ff781b0'
down_revision: Union[str, Sequence[str], None] = '450f0960a5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_finance_requests_id'), table_name='finance_requests')
    op.drop_table('finance_requests')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_credit_score_requests_id'), table_name='credit_score_requests')
    op.drop_table('credit_score_requests')
    op.drop_index(op.f('ix_smes_id'), table_name='smes')
    op.drop_table('smes')
    op.drop_index(op.f('ix_credit_scores_id'), table_name='credit_scores')
    op.drop_table('credit_scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('applicant_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('monthly_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('monthly_expenses', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('loan_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('credit_history_years', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('missed_payments', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credit_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_scores_pkey'))
    )
    op.create_index(op.f('ix_credit_scores_id'), 'credit_scores', ['id'], unique=False)
    op.create_table('smes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('smes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expenses', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('credit_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='smes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_smes_id'), 'smes', ['id'], unique=False)
    op.create_table('credit_score_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sme_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], name=op.f('credit_score_requests_sme_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_score_requests_pkey'))
    )
    op.create_index(op.f('ix_credit_score_requests_id'), 'credit_score_requests', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sme_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], name=op.f('invoices_sme_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invoices_pkey'))
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('finance_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sme_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_requested', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], name=op.f('finance_requests_sme_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('finance_requests_pkey'))
    )
    op.create_index(op.f('ix_finance_requests_id'), 'finance_requests', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
